#ifndef CLICKFOLDER_H
#define CLICKFOLDER_H


enum ClickFolder {
    PLAYER_1_CLICKS,
    PLAYER_1_RELEASES,
    PLAYER_1_SOFTCLICKS,
    PLAYER_1_SOFTRELEASES,
    PLAYER_1_HARDCLICKS,
    PLAYER_1_HARDRELEASES,
    PLAYER_1_MICROCLICKS,
    PLAYER_1_MICRORELEASES,

    PLAYER_1_LEFTCLICKS,
    PLAYER_1_LEFTRELEASES,
    PLAYER_1_LEFTSOFTCLICKS,
    PLAYER_1_LEFTSOFTRELEASES,
    PLAYER_1_LEFTHARDCLICKS,
    PLAYER_1_LEFTHARDRELEASES,
    PLAYER_1_LEFTMICROCLICKS,
    PLAYER_1_LEFTMICRORELEASES,

    PLAYER_1_RIGHTCLICKS,
    PLAYER_1_RIGHTRELEASES,
    PLAYER_1_RIGHTSOFTCLICKS,
    PLAYER_1_RIGHTSOFTRELEASES,
    PLAYER_1_RIGHTHARDCLICKS,
    PLAYER_1_RIGHTHARDRELEASES,
    PLAYER_1_RIGHTMICROCLICKS,
    PLAYER_1_RIGHTMICRORELEASES,

    PLAYER_2_CLICKS,
    PLAYER_2_RELEASES,
    PLAYER_2_SOFTCLICKS,
    PLAYER_2_SOFTRELEASES,
    PLAYER_2_HARDCLICKS,
    PLAYER_2_HARDRELEASES,
    PLAYER_2_MICROCLICKS,
    PLAYER_2_MICRORELEASES,

    PLAYER_2_LEFTCLICKS,
    PLAYER_2_LEFTRELEASES,
    PLAYER_2_LEFTSOFTCLICKS,
    PLAYER_2_LEFTSOFTRELEASES,
    PLAYER_2_LEFTHARDCLICKS,
    PLAYER_2_LEFTHARDRELEASES,
    PLAYER_2_LEFTMICROCLICKS,
    PLAYER_2_LEFTMICRORELEASES,

    PLAYER_2_RIGHTCLICKS,
    PLAYER_2_RIGHTRELEASES,
    PLAYER_2_RIGHTSOFTCLICKS,
    PLAYER_2_RIGHTSOFTRELEASES,
    PLAYER_2_RIGHTHARDCLICKS,
    PLAYER_2_RIGHTHARDRELEASES,
    PLAYER_2_RIGHTMICROCLICKS,
    PLAYER_2_RIGHTMICRORELEASES,
};

#endif // CLICKFOLDER_H
